[id]
type = snr
version = v1.0

[global]
jy0mag = 3200.0
lambda = 600.0
topt = 280.0
emis = 0.05
rdnoise = 2.8
gain = 0.0145
bandpass = 200.0
pixel = 5.86
sky = 18.5
dark = 0.241
cy = 1.5
zenith = 0.0
alt = 1200.0
hscale = 8000.0
objrad = 1.0
seeing = 3.0

# System specifications
[SW16]
name = SkyWatcher 16
aper = 40.6
fnum = 4.4
tput = 0.4

[SW8]
name = SkyWatcher 8
aper = 20.3
fnum = 5.9
tput = 0.4

[C11]
name = CPC1100 + 0.5x FR
aper = 27.94
fnum = 5.5
tput = 0.4

[C11h]
name = CPC1100 + Hyperstar
aper = 27.94
fnum = 1.93
tput = 0.4
# Double the predicted value for C11
snrscale = 2.0

[UL20]
name = Hubble Optics UL20
aper = 50.8
fnum = 3.72
tput = 0.4

